In [3]:
import tensorflow as tf
from tensorflow.keras import models, datasets, layers
import matplotlib.pyplot as plt
import numpy as np

In [7]:
(x_train, y_train) , (x_test, y_test) = datasets.cifar10.load_data()

170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 135s 1us/step


In [15]:
x_train[0].shape

(32, 32, 3)

In [17]:
y_train[0]

array([6], dtype=uint8)

In [19]:
y_train

array([[6],
       [9],
       [9],
       ...,
       [9],
       [1],
       [1]], dtype=uint8)

In [21]:
y_train = y_train.reshape(-1)
y_test = y_test.reshape(-1)

In [23]:
y_test

array([3, 8, 8, ..., 5, 1, 7], dtype=uint8)

In [25]:
x_train = x_train / 255
x_test = x_test / 255

In [27]:
classes = ["airplane","automobile","bird","cat","deer","dog","frog","horse","ship","truck"]

In [37]:
ann = models.Sequential([
    layers.Flatten(input_shape= (32,32,3)),
    layers.Dense(3000, activation='relu'),
    layers.Dense(1000, activation='relu'),
    layers.Dense(10, activation = 'softmax')
])
ann.compile(optimizer='SGD',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

ann.fit(x_train, y_train, epochs=5)

Epoch 1/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 41s 24ms/step - accuracy: 0.3043 - loss: 1.9336
Epoch 2/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 37s 24ms/step - accuracy: 0.4205 - loss: 1.6421
Epoch 3/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 40s 25ms/step - accuracy: 0.4544 - loss: 1.5524
Epoch 4/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 37s 24ms/step - accuracy: 0.4722 - loss: 1.4902
Epoch 5/5
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 37s 23ms/step - accuracy: 0.4932 - loss: 1.4442


In [41]:
from sklearn.metrics import confusion_matrix , classification_report
y_pred = ann.predict(x_test)
y_pred_classes = [np.argmax(element) for element in y_pred]

print("Classification Report: \n", classification_report(y_test, y_pred_classes))

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step
Classification Report: 
               precision    recall  f1-score   support

           0       0.59      0.48      0.53      1000
           1       0.68      0.54      0.60      1000
           2       0.28      0.55      0.37      1000
           3       0.38      0.21      0.27      1000
           4       0.41      0.35      0.38      1000
           5       0.37      0.40      0.39      1000
           6       0.43      0.68      0.52      1000
           7       0.65      0.41      0.51      1000
           8       0.70      0.50      0.58      1000
           9       0.56      0.58      0.57      1000

    accuracy                           0.47     10000
   macro avg       0.51      0.47      0.47     10000
weighted avg       0.51      0.47      0.47     10000



In [57]:
cnn = models.Sequential([
    layers.Conv2D(input_shape = (32,32,3), activation = 'relu', filters= 32, kernel_size=(3,3)),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(activation = 'relu', filters= 64, kernel_size=(3,3)),
    layers.MaxPooling2D((2,2)),

    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation = 'softmax')
])

cnn.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

cnn.fit(x_train, y_train, epochs=10)

C:\Users\Asus\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 19s 10ms/step - accuracy: 0.3820 - loss: 1.6913
Epoch 2/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 15s 9ms/step - accuracy: 0.5887 - loss: 1.1575
Epoch 3/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 18s 12ms/step - accuracy: 0.6454 - loss: 1.0138
Epoch 4/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 16s 10ms/step - accuracy: 0.6801 - loss: 0.9246
Epoch 5/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 16s 10ms/step - accuracy: 0.7053 - loss: 0.8506
Epoch 6/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 17s 11ms/step - accuracy: 0.7215 - loss: 0.7970
Epoch 7/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 19s 10ms/step - accuracy: 0.7431 - loss: 0.7488
Epoch 8/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 18s 11ms/step - accuracy: 0.7490 - loss: 0.7180
Epoch 9/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 15s 10ms/step - accuracy: 0.7663 - loss: 0.6739
Epoch 10/10
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 16s 10ms/step - accuracy: 0.7814 - loss: 0.6303


In [58]:
cnn.evaluate(x_test,y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7019 - loss: 0.8831


[0.9006969928741455, 0.6974999904632568]

In [60]:
from sklearn.metrics import confusion_matrix , classification_report
y_pred = cnn.predict(x_test)
y_pred_classes = [np.argmax(element) for element in y_pred]

print("Classification Report: \n", classification_report(y_test, y_pred_classes))

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step
Classification Report: 
               precision    recall  f1-score   support

           0       0.74      0.75      0.75      1000
           1       0.81      0.82      0.81      1000
           2       0.54      0.65      0.59      1000
           3       0.48      0.53      0.51      1000
           4       0.70      0.59      0.64      1000
           5       0.64      0.56      0.60      1000
           6       0.71      0.81      0.76      1000
           7       0.77      0.72      0.74      1000
           8       0.86      0.76      0.81      1000
           9       0.81      0.78      0.80      1000

    accuracy                           0.70     10000
   macro avg       0.70      0.70      0.70     10000
weighted avg       0.70      0.70      0.70     10000

